/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2021-01-11 08:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.Random;
import com.balaji.travels.*;

public final class VT_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header.html", Long.valueOf(1555790780216L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1555790848287L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.balaji.travels");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0; maximum-scale=1\">\r\n");
      out.write("<meta name=\"author\" content=\"ADITYA\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.png\">\r\n");
      out.write("<title>Wecome To Bus Booking Portal</title>\r\n");
      out.write("<!-- Reset CSS -->\r\n");
      out.write("<link href=\"css/reset.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"css/fonts.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Select2 -->\r\n");
      out.write("<link href=\"css/select2.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link href=\"css/magnific-popup.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Iconmoon -->\r\n");
      out.write("<link href=\"css/iconmoon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<link href=\"css/owl.carousel.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Animate -->\r\n");
      out.write("<link href=\"css/animate.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Custom Style -->\r\n");
      out.write("<link href=\"css/custom.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/site.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"css/jquerysctipttop.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/feedback.css\" />\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground-color: #f2f2f2;\r\n");
      out.write("\t\tfont-family: helvetica,arial,tahoma,verdana,sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\th1{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top: 40px;\r\n");
      out.write("\t\tcolor: #333;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Start Header -->\r\n");
      out.write("<header> \r\n");
      out.write("  <!-- Start Header top Bar -->\r\n");
      out.write("  <div class=\"header-top\">\r\n");
      out.write("    <div class=\"container clearfix\">\r\n");
      out.write("  \r\n");
      out.write("    <font color=\"White\"><b><marquee >Welcome &nbsp To &nbsp SRI BALAJI &nbsp Travels..</b></marquee>\r\n");
      out.write("      <div class=\"right-block clearfix\">\r\n");
      out.write("        <ul class=\"top-nav\">\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- End Header top Bar --> \r\n");
      out.write("  <!-- Start Header Middle -->\r\n");
      out.write("  <div class=\"container header-middle\">\r\n");
      out.write("  <div class=\"row\"> <span class=\"col-xs-6 col-sm-2\"><img src=\"Images/logo.jpg\" class=\"img-responsive\" alt=\"\"></a></span>\r\n");
      out.write("  \r\n");
      out.write("     <div class=\"col-xs-6 col-sm-9\"></div>\r\n");
      out.write("      <div class=\"col-xs-6 col-sm-9\">\r\n");
      out.write("        <div class=\"contact clearfix\">\r\n");
      out.write("          <ul class=\"hidden-xs\">\r\n");
      out.write("         <li><h4>Welcome to </h4><h2>SRI BALAJI travels</h2></li>\r\n");
      out.write("            <li> <span>Email</span> <a href=\"mailto:apscadi@gmail.com\">Drop a Mail </a> </li>\r\n");
      out.write("            <li> <span>Mobile</span> +91 99 536 42400 </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("    </div></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- End Header Middle --> \r\n");
      out.write("  <!-- Start Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("        <button aria-controls=\"navbar\" aria-expanded=\"false\" data-target=\"#navbar\" data-toggle=\"collapse\" class=\"navbar-toggle collapsed\" type=\"button\"> <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"navbar-collapse collapse\" id=\"navbar\">\r\n");
      out.write("        \r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("          <li> <a href=\"UserPage.jsp\">Home</a></li>\r\n");
      out.write("          \r\n");
      out.write("\t\t <li class=\"dropdown\"> <a data-toggle=\"dropdown\" href=\"UserLogin.jsp\">Book Now <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("            \r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"dropdown\"> <a data-toggle=\"dropdown\" href=\"AboutUs.jsp\">About Us <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("            \r\n");
      out.write("          </li>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <li class=\"dropdown\"> <a data-toggle=\"dropdown\" href=\"ContactUs.jsp\">Contact Us <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("           \r\n");
      out.write("          </li>\r\n");
      out.write("\t\t  <li class=\"dropdown\"> <a data-toggle=\"dropdown\" href=\"UserRegisterPage.jsp\">Register <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("           \r\n");
      out.write("          </li>\r\n");
      out.write("\t\t  <li class=\"dropdown\"> <a data-toggle=\"dropdown\" href=\"VR.jsp\">View Routes <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("           \r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"dropdown\"> <a data-toggle=\"dropdown\" href=\"Feedback.jsp\">Give Testimonial <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("           \r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("\t\t \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- End Navigation --> \r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<HEAD>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script LANGUAGE=\"Javascript\" SRC=\"Images/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("<h2 align=center style=\"color:Red; font-family: Ariel; font-size: 250%;\">Testimonials</h2>\r\n");
      out.write("\r\n");


	Connection con=null;
	ResultSet rs=null;
	Statement stmt=null;
	try{
			
			
			con = ConnectionPool.getConnection();
			stmt =  con.createStatement();

			String Query = "Select Feedback from feedback order by `FId`";
			rs = stmt.executeQuery(Query);
			
      out.write("<marquee direction = \"up\" scrollamount=\"3\" scrollspeed=\"100\">\r\n");
      out.write("\t\t\t\t\t\t<table align=\"center\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

			int rCount=0;
			while(rs.next())
			{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr class= ");
      out.print((rCount%2!=0)? "row_even" : "row_odd");
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

				rCount++;
			}
			if( rCount == 0)	{
      out.write("<h3 align=center>Sorry No records Found</h3>");
 }
			rs.close();
			stmt.close();
			con.close();
		}catch(Exception e){
			rs.close();
			stmt.close();
			con.close();
			
      out.print(e);

		}
	

      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- Start Footer -->\r\n");
      out.write("<footer class=\"footer\"> \r\n");
      out.write("  <!-- Start Footer Top -->\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row row1\">\r\n");
      out.write("      <div class=\"col-sm-9 clearfix\">\r\n");
      out.write("        <div class=\"foot-nav\">\r\n");
      out.write("          <h3>Connect With BALAJI TRAVELS</h3>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">BALAJI</a></li>\r\n");
      out.write("            <li><a href=\"#\">FACEBOOK</a></li>\r\n");
      out.write("            <li><a href=\"#\">INSTAGRAM</a></li>\r\n");
      out.write("            <li><a href=\"#\">TWITTER</a></li>\r\n");
      out.write("           \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"foot-nav\">\r\n");
      out.write("          <h3>Contact Us</h3>\r\n");
      out.write("          <ul>\r\n");
      out.write("             <li><a href=\"https://www.facebook.com/\">Subhanshu Shukla</a></li>\r\n");
      out.write("              <li><a href=\"https://www.facebook.com/aadityaathaakur\"></a></li>\r\n");
      out.write("              <li><a href=\"https://www.facebook.com/avinashsharma19895\"></a></li>\r\n");
      out.write("              \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"foot-nav\">\r\n");
      out.write("          <h3>Why BALAJI Travels</h3>\r\n");
      out.write("          \r\n");
      out.write("          <ul>\r\n");
      out.write("          <li><a href=\"UserLogin.jsp\">Book Bus tickets to more than 200 cities.</a></li>\r\n");
      out.write("              <li><a href=\"UserLogin.jsp\">Cancellation is possible on the net.</a></li>\r\n");
      out.write("              <li><a href=\"UserLogin.jsp\">Pay using Major Credit/Debit Card</a></li>\r\n");
      out.write("              \r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"foot-nav\">\r\n");
      out.write("          <h3>          More On SRIBALAJI  travels</h3>\r\n");
      out.write("         <ul> <li><a href=\"#\">ABOUT Us</a></li>\r\n");
      out.write("          <li><a href=\"#\">View Routes</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-3\">\r\n");
      out.write("        <div class=\"footer-logo hidden-xs\"><a href=\"index-2.php\"><img src=\"Images/logo.jpg\" class=\"img-responsive\" alt=\"\"></a></div>\r\n");
      out.write("        <p>© 2018 <span>SRIBALAJI travels</span>. All rights reserved</p>\r\n");
      out.write("        <ul class=\"terms clearfix\">\r\n");
      out.write("          <li><a href=\"#l\">TERMS OF USE</a></li>\r\n");
      out.write("          <li><a href=\"#\">PRIVACY POLICY</a></li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- End Footer Top --> \r\n");
      out.write("  \r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End Footer --> \r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
